[tool.poetry]
name = "ZEON-Refiller"
version = "1.0.0"
description = ""
authors = ["Air Erik <airerik@yandex.ru>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
