apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zeon-refiller

resources:
  - ../../base

patches:
  - path: patch-configmap-vm-prefix.yaml
    # Целевой файл опционален. Но лучше указать
    target:
      kind: ConfigMap
      name: zeon-refiller-config
