apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeon-refiller-deployment
  namespace: zeon-refiller
  labels:
    app: zeon-refiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeon-refiller
  template:
    metadata:
      labels:
        app: zeon-refiller
    spec:
      # ─── Общий securityContext для Pod ───
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: zeon-refiller
          image: airerik/zeon-refiller:latest
          imagePullPolicy: IfNotPresent

          # ─── Указываем, от какого UID запускать контейнер ───
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          resources:
            requests:
              cpu:    "100m"
              memory: "128Mi"
            limits:
              cpu:    "500m"
              memory: "512Mi"
