apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeon-refiller-deployment
  namespace: zeon-refiller
  labels:
    app: zeon-refiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeon-refiller
  template:
    metadata:
      labels:
        app: zeon-refiller
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
      containers:
        - name: zeon-refiller
          image: airerik/zeon-refiller:v1.0.7
          imagePullPolicy: IfNotPresent

          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

          resources:
            requests:
              cpu:    "100m"
              memory: "128Mi"
            limits:
              cpu:    "500m"
              memory: "512Mi"
