apiVersion: v1
kind: Secret
metadata:
  name: zeon-refiller-secret
  namespace: zeon-refiller
type: Opaque
data:
  VCENTER_USER: "administrator@zeon.loc"
  VCENTER_PASSWORD: "Tf34gfasz!"
  NSX_USER: "admin"
  NSX_PASSWORD: "C5QPrnP6!!!!"
