apiVersion: v1
kind: ConfigMap
metadata:
  name: vsphere-config
data:
  VS_PHERE_HOST: "dev-vcenter.example.com"
  VS_PHERE_USER: "dev_user"
  VS_PHERE_PASSWORD: "dev_password"
  VS_PHERE_PORT: "443"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeon-refiller-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: zeon-refiller
          image: airerik/zeon-refiller:dev
